### PR TITLE
chore: change CODEOWNERS to qx-team

### PR DESCRIPTION
**Pull request by rockstar**

### CODE REVIEW

**Review by onelson — APPROVED** [review]
> "This CODEOWNERS file contains errors ..."

Does `qx-team` not exist yet?

**Comment by rockstar** [comment]
It does. https://github.com/orgs/influxdata/teams/qx-team/ Where are you seeing that error? I can't get team to show up in the review request box, so something is missing.

**Comment by onelson** [comment]
> Where are you seeing that error?

Header above the file when you look at the diff

image

**Review by nathanielc — APPROVED** [review]

**Comment by nathanielc** [comment]
I fixed the write access issue

**Pull request merged**
